services:
  ipfs:
    image: ipfs/go-ipfs:master-2021-03-24-3f9c3f4
    restart: always
    ports:
      - 8080:8080
      - 5001:5001
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fleek
      POSTGRES_PASSWORD: fleek-password
      POSTGRES_DB: assignment
    ports:
      - 5432:5432
    volumes:
      - ./packages/server/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
