name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.3.x'
      - name: Install
        run: yarn
      - name: Format
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
